### ISSUE TITLE
can i use For Valorant like this

### ISSUE THREAD

**Issue by FranklinOP-IND** [masterpastaa/Face-Injector-V3#4]
![image](https://user-images.githubusercontent.com/64591314/163414061-da205a12-9313-43e8-a69c-11f7ce525db1.png)

**Comment by GODXiE** [comment]
how did you solve time_t warning :(

**Comment by FranklinOP-IND** [comment]
i don't have any error

**Comment by GODXiE** [comment]
when i try to release , C2664 'time_t time(time_t *const )' : 1 bağımsız değişkeni 'time_t' değerinden 'time_t *const ' değerine dönüştürülemez face_injector_v3 :S

**Comment by MadrisAkb** [comment]
Just delete

> when i try to release , C2664 'time_t time(time_t *const )' : 1 bağımsız değişkeni 'time_t' değerinden 'time_t *const ' değerine dönüştürülemez face_injector_v3 :S

Just delete  it and will be done

**Comment by Pinguu-dev** [comment]
`std::vector<TargetProcess> Target::potential_targets = {
	{ "Valorant", "VALORANT-Win64-Shipping.exe", "test.dll", X64, false },
};`

**Comment by FranklinOP-IND** [comment]
> 

Thanx Bro
